//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionCoreCableColor.DbConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SoporteOPEntities : DbContext
    {
        public SoporteOPEntities()
            : base("name=SoporteOPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<string> dt_addtosourcecontrol(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("dt_addtosourcecontrol", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual ObjectResult<string> dt_addtosourcecontrol_u(string vchSourceSafeINI, string vchProjectName, string vchComment, string vchLoginName, string vchPassword)
        {
            var vchSourceSafeINIParameter = vchSourceSafeINI != null ?
                new ObjectParameter("vchSourceSafeINI", vchSourceSafeINI) :
                new ObjectParameter("vchSourceSafeINI", typeof(string));
    
            var vchProjectNameParameter = vchProjectName != null ?
                new ObjectParameter("vchProjectName", vchProjectName) :
                new ObjectParameter("vchProjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("dt_addtosourcecontrol_u", vchSourceSafeINIParameter, vchProjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_adduserobject()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject");
        }
    
        public virtual int dt_adduserobject_vcs(string vchProperty)
        {
            var vchPropertyParameter = vchProperty != null ?
                new ObjectParameter("vchProperty", vchProperty) :
                new ObjectParameter("vchProperty", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_adduserobject_vcs", vchPropertyParameter);
        }
    
        public virtual int dt_checkinobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkinobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag, string txStream1, string txStream2, string txStream3)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            var txStream1Parameter = txStream1 != null ?
                new ObjectParameter("txStream1", txStream1) :
                new ObjectParameter("txStream1", typeof(string));
    
            var txStream2Parameter = txStream2 != null ?
                new ObjectParameter("txStream2", txStream2) :
                new ObjectParameter("txStream2", typeof(string));
    
            var txStream3Parameter = txStream3 != null ?
                new ObjectParameter("txStream3", txStream3) :
                new ObjectParameter("txStream3", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkinobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter, txStream1Parameter, txStream2Parameter, txStream3Parameter);
        }
    
        public virtual int dt_checkoutobject(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_checkoutobject_u(string chObjectType, string vchObjectName, string vchComment, string vchLoginName, string vchPassword, Nullable<int> iVCSFlags, Nullable<int> iActionFlag)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchCommentParameter = vchComment != null ?
                new ObjectParameter("vchComment", vchComment) :
                new ObjectParameter("vchComment", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iVCSFlagsParameter = iVCSFlags.HasValue ?
                new ObjectParameter("iVCSFlags", iVCSFlags) :
                new ObjectParameter("iVCSFlags", typeof(int));
    
            var iActionFlagParameter = iActionFlag.HasValue ?
                new ObjectParameter("iActionFlag", iActionFlag) :
                new ObjectParameter("iActionFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_checkoutobject_u", chObjectTypeParameter, vchObjectNameParameter, vchCommentParameter, vchLoginNameParameter, vchPasswordParameter, iVCSFlagsParameter, iActionFlagParameter);
        }
    
        public virtual int dt_displayoaerror(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_displayoaerror_u(Nullable<int> iObject, Nullable<int> iresult)
        {
            var iObjectParameter = iObject.HasValue ?
                new ObjectParameter("iObject", iObject) :
                new ObjectParameter("iObject", typeof(int));
    
            var iresultParameter = iresult.HasValue ?
                new ObjectParameter("iresult", iresult) :
                new ObjectParameter("iresult", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_displayoaerror_u", iObjectParameter, iresultParameter);
        }
    
        public virtual int dt_droppropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_droppropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual int dt_dropuserobjectbyid(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_dropuserobjectbyid", idParameter);
        }
    
        public virtual int dt_generateansiname(ObjectParameter name)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_generateansiname", name);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop(string property, string value)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop", propertyParameter, valueParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> dt_getobjwithprop_u(string property, string uvalue)
        {
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_getobjwithprop_u", propertyParameter, uvalueParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_Result> dt_getpropertiesbyid(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_Result>("dt_getpropertiesbyid", idParameter, propertyParameter);
        }
    
        public virtual ObjectResult<dt_getpropertiesbyid_u_Result> dt_getpropertiesbyid_u(Nullable<int> id, string property)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<dt_getpropertiesbyid_u_Result>("dt_getpropertiesbyid_u", idParameter, propertyParameter);
        }
    
        public virtual int dt_getpropertiesbyid_vcs(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_getpropertiesbyid_vcs_u(Nullable<int> id, string property, ObjectParameter value)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_getpropertiesbyid_vcs_u", idParameter, propertyParameter, value);
        }
    
        public virtual int dt_isundersourcecontrol(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_isundersourcecontrol_u(string vchLoginName, string vchPassword, Nullable<int> iWhoToo)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            var iWhoTooParameter = iWhoToo.HasValue ?
                new ObjectParameter("iWhoToo", iWhoToo) :
                new ObjectParameter("iWhoToo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_isundersourcecontrol_u", vchLoginNameParameter, vchPasswordParameter, iWhoTooParameter);
        }
    
        public virtual int dt_removefromsourcecontrol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_removefromsourcecontrol");
        }
    
        public virtual int dt_setpropertybyid(Nullable<int> id, string property, string value, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var valueParameter = value != null ?
                new ObjectParameter("value", value) :
                new ObjectParameter("value", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid", idParameter, propertyParameter, valueParameter, lvalueParameter);
        }
    
        public virtual int dt_setpropertybyid_u(Nullable<int> id, string property, string uvalue, byte[] lvalue)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var propertyParameter = property != null ?
                new ObjectParameter("property", property) :
                new ObjectParameter("property", typeof(string));
    
            var uvalueParameter = uvalue != null ?
                new ObjectParameter("uvalue", uvalue) :
                new ObjectParameter("uvalue", typeof(string));
    
            var lvalueParameter = lvalue != null ?
                new ObjectParameter("lvalue", lvalue) :
                new ObjectParameter("lvalue", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_setpropertybyid_u", idParameter, propertyParameter, uvalueParameter, lvalueParameter);
        }
    
        public virtual int dt_validateloginparams(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_validateloginparams_u(string vchLoginName, string vchPassword)
        {
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_validateloginparams_u", vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int dt_vcsenabled()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("dt_vcsenabled");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp006()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp006");
        }
    
        public virtual ObjectResult<Nullable<int>> dt_verstamp007()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("dt_verstamp007");
        }
    
        public virtual ObjectResult<string> dt_whocheckedout(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("dt_whocheckedout", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual ObjectResult<string> dt_whocheckedout_u(string chObjectType, string vchObjectName, string vchLoginName, string vchPassword)
        {
            var chObjectTypeParameter = chObjectType != null ?
                new ObjectParameter("chObjectType", chObjectType) :
                new ObjectParameter("chObjectType", typeof(string));
    
            var vchObjectNameParameter = vchObjectName != null ?
                new ObjectParameter("vchObjectName", vchObjectName) :
                new ObjectParameter("vchObjectName", typeof(string));
    
            var vchLoginNameParameter = vchLoginName != null ?
                new ObjectParameter("vchLoginName", vchLoginName) :
                new ObjectParameter("vchLoginName", typeof(string));
    
            var vchPasswordParameter = vchPassword != null ?
                new ObjectParameter("vchPassword", vchPassword) :
                new ObjectParameter("vchPassword", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("dt_whocheckedout_u", chObjectTypeParameter, vchObjectNameParameter, vchLoginNameParameter, vchPasswordParameter);
        }
    
        public virtual int sp_Actualizar_InfoPlacaIP(string pcPlaca, Nullable<int> piPeriodo, Nullable<decimal> pnMultaVehicularDebito, Nullable<decimal> pnMultaVehicularCredito)
        {
            var pcPlacaParameter = pcPlaca != null ?
                new ObjectParameter("pcPlaca", pcPlaca) :
                new ObjectParameter("pcPlaca", typeof(string));
    
            var piPeriodoParameter = piPeriodo.HasValue ?
                new ObjectParameter("piPeriodo", piPeriodo) :
                new ObjectParameter("piPeriodo", typeof(int));
    
            var pnMultaVehicularDebitoParameter = pnMultaVehicularDebito.HasValue ?
                new ObjectParameter("pnMultaVehicularDebito", pnMultaVehicularDebito) :
                new ObjectParameter("pnMultaVehicularDebito", typeof(decimal));
    
            var pnMultaVehicularCreditoParameter = pnMultaVehicularCredito.HasValue ?
                new ObjectParameter("pnMultaVehicularCredito", pnMultaVehicularCredito) :
                new ObjectParameter("pnMultaVehicularCredito", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Actualizar_InfoPlacaIP", pcPlacaParameter, piPeriodoParameter, pnMultaVehicularDebitoParameter, pnMultaVehicularCreditoParameter);
        }
    
        public virtual int sp_BandejaRequerimiento(Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_BandejaRequerimiento", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<SP_CallCenter_Oferta_Result> SP_CallCenter_Oferta(Nullable<decimal> pnObligaciones)
        {
            var pnObligacionesParameter = pnObligaciones.HasValue ?
                new ObjectParameter("pnObligaciones", pnObligaciones) :
                new ObjectParameter("pnObligaciones", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CallCenter_Oferta_Result>("SP_CallCenter_Oferta", pnObligacionesParameter);
        }
    
        public virtual int sp_Catalogo_Manuales_Eliminar_Pagina(Nullable<int> piIDManual, Nullable<int> piIDPagina, Nullable<int> piIDorden, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDManualParameter = piIDManual.HasValue ?
                new ObjectParameter("piIDManual", piIDManual) :
                new ObjectParameter("piIDManual", typeof(int));
    
            var piIDPaginaParameter = piIDPagina.HasValue ?
                new ObjectParameter("piIDPagina", piIDPagina) :
                new ObjectParameter("piIDPagina", typeof(int));
    
            var piIDordenParameter = piIDorden.HasValue ?
                new ObjectParameter("piIDorden", piIDorden) :
                new ObjectParameter("piIDorden", typeof(int));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Catalogo_Manuales_Eliminar_Pagina", piIDManualParameter, piIDPaginaParameter, piIDordenParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> sp_Catalogo_Manuales_Guardar(Nullable<int> piIDUsuarioCreador, string pcTitulo, string pcDescripcion, Nullable<int> piIDTipoManual, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDUsuarioCreadorParameter = piIDUsuarioCreador.HasValue ?
                new ObjectParameter("piIDUsuarioCreador", piIDUsuarioCreador) :
                new ObjectParameter("piIDUsuarioCreador", typeof(int));
    
            var pcTituloParameter = pcTitulo != null ?
                new ObjectParameter("pcTitulo", pcTitulo) :
                new ObjectParameter("pcTitulo", typeof(string));
    
            var pcDescripcionParameter = pcDescripcion != null ?
                new ObjectParameter("pcDescripcion", pcDescripcion) :
                new ObjectParameter("pcDescripcion", typeof(string));
    
            var piIDTipoManualParameter = piIDTipoManual.HasValue ?
                new ObjectParameter("piIDTipoManual", piIDTipoManual) :
                new ObjectParameter("piIDTipoManual", typeof(int));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("sp_Catalogo_Manuales_Guardar", piIDUsuarioCreadorParameter, pcTituloParameter, pcDescripcionParameter, piIDTipoManualParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual int sp_Catalogo_Manuales_Guardar_Manual(Nullable<int> piIDManual, string pcTitulo, string pcDescripcion, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDManualParameter = piIDManual.HasValue ?
                new ObjectParameter("piIDManual", piIDManual) :
                new ObjectParameter("piIDManual", typeof(int));
    
            var pcTituloParameter = pcTitulo != null ?
                new ObjectParameter("pcTitulo", pcTitulo) :
                new ObjectParameter("pcTitulo", typeof(string));
    
            var pcDescripcionParameter = pcDescripcion != null ?
                new ObjectParameter("pcDescripcion", pcDescripcion) :
                new ObjectParameter("pcDescripcion", typeof(string));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Catalogo_Manuales_Guardar_Manual", piIDManualParameter, pcTituloParameter, pcDescripcionParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual int sp_Catalogo_Manuales_Guardar_Pagina(Nullable<int> piIDManual, Nullable<int> piIDPagina, Nullable<int> piIDorden, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDManualParameter = piIDManual.HasValue ?
                new ObjectParameter("piIDManual", piIDManual) :
                new ObjectParameter("piIDManual", typeof(int));
    
            var piIDPaginaParameter = piIDPagina.HasValue ?
                new ObjectParameter("piIDPagina", piIDPagina) :
                new ObjectParameter("piIDPagina", typeof(int));
    
            var piIDordenParameter = piIDorden.HasValue ?
                new ObjectParameter("piIDorden", piIDorden) :
                new ObjectParameter("piIDorden", typeof(int));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Catalogo_Manuales_Guardar_Pagina", piIDManualParameter, piIDPaginaParameter, piIDordenParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_CatalogoManual_Detalle_Listado_Result> sp_CatalogoManual_Detalle_Listado(Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CatalogoManual_Detalle_Listado_Result>("sp_CatalogoManual_Detalle_Listado", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_CatalogoManual_Documento_ObtenerPorIDManual_Result> sp_CatalogoManual_Documento_ObtenerPorIDManual(Nullable<int> piIDManual, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDManualParameter = piIDManual.HasValue ?
                new ObjectParameter("piIDManual", piIDManual) :
                new ObjectParameter("piIDManual", typeof(int));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CatalogoManual_Documento_ObtenerPorIDManual_Result>("sp_CatalogoManual_Documento_ObtenerPorIDManual", piIDManualParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual int sp_CatalogoManual_Eliminar(Nullable<int> piIDManual, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDManualParameter = piIDManual.HasValue ?
                new ObjectParameter("piIDManual", piIDManual) :
                new ObjectParameter("piIDManual", typeof(int));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_CatalogoManual_Eliminar", piIDManualParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_CatalogoManual_IDUltimo_Creado(Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_CatalogoManual_IDUltimo_Creado", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_CatalogoManual_Listado_Result> sp_CatalogoManual_Listado(Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CatalogoManual_Listado_Result>("sp_CatalogoManual_Listado", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_CatalogoManual_Listado_IDManual_Result> sp_CatalogoManual_Listado_IDManual(Nullable<int> piIDManual, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDManualParameter = piIDManual.HasValue ?
                new ObjectParameter("piIDManual", piIDManual) :
                new ObjectParameter("piIDManual", typeof(int));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_CatalogoManual_Listado_IDManual_Result>("sp_CatalogoManual_Listado_IDManual", piIDManualParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual int sp_Eliminar_InfoPlacaIP(string pcPlaca)
        {
            var pcPlacaParameter = pcPlaca != null ?
                new ObjectParameter("pcPlaca", pcPlaca) :
                new ObjectParameter("pcPlaca", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Eliminar_InfoPlacaIP", pcPlacaParameter);
        }
    
        public virtual ObjectResult<sp_Estados_Requerimiento_Result> sp_Estados_Requerimiento(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Estados_Requerimiento_Result>("sp_Estados_Requerimiento", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual int sp_GPSMonitoreo_CargarJSON()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_GPSMonitoreo_CargarJSON");
        }
    
        public virtual int sp_IncertarConsultaPlacaIP(string pcPlaca, string pcMarca, string pcColor, Nullable<int> pilDPeriodo, Nullable<decimal> pnTasaVehicularDebito, Nullable<decimal> pnTasaVehicularCredito, Nullable<decimal> pnTasaVehicularSaldo, Nullable<decimal> pnMultaVehicularDebito, Nullable<decimal> pnMultaVehicularCredito, Nullable<decimal> pnMultaVehicularSaldo, Nullable<decimal> pnSaldosAnterioresVehicularDebito, Nullable<decimal> pnSaldosAnterioresVehicularCredito, Nullable<decimal> pnSaldosAnterioresVehicularSaldo, Nullable<decimal> pnTasaMunicipalDebito, Nullable<decimal> pnTasaMunicipalCredito, Nullable<decimal> pnTasaMunicipalSaldo, Nullable<decimal> pnMultaMunicipalDebito, Nullable<decimal> pnMultaMunicipalCredito, Nullable<decimal> pnMultaMunicipalSaldo, Nullable<decimal> pnSaldosAnterioresMunicipalesDebito, Nullable<decimal> pnSaldosAnterioresMunicipalesCredito, Nullable<decimal> pnSaldosAnterioresMunicipalesSaldo, Nullable<decimal> pnContribucionSigloXXIDebito, Nullable<decimal> pnContribucionSigloXXICredito, Nullable<decimal> pnContribucionSigloXXISaldo, Nullable<decimal> pnSaldosAnterioresSigloXXIDebito, Nullable<decimal> pnSaldosAnterioresSiglosXXICredito, Nullable<decimal> pnSaldosAnterioresSiglosXXISaldo, Nullable<decimal> pnValorPlacaDebito, Nullable<decimal> pnValorPlacaCredito, Nullable<decimal> pnValorPlacaSaldo, Nullable<decimal> pilDTotalMatricula, Nullable<int> piCambiodePropietarioCantidad, Nullable<decimal> pnCambiodePropietarioMonto, Nullable<int> piCambioPlacaCantidad, Nullable<decimal> pnCambioPlacaMonto, Nullable<int> piTotalCantidad, Nullable<decimal> pnTotalMonto, Nullable<decimal> pnTotalaPagar)
        {
            var pcPlacaParameter = pcPlaca != null ?
                new ObjectParameter("pcPlaca", pcPlaca) :
                new ObjectParameter("pcPlaca", typeof(string));
    
            var pcMarcaParameter = pcMarca != null ?
                new ObjectParameter("pcMarca", pcMarca) :
                new ObjectParameter("pcMarca", typeof(string));
    
            var pcColorParameter = pcColor != null ?
                new ObjectParameter("pcColor", pcColor) :
                new ObjectParameter("pcColor", typeof(string));
    
            var pilDPeriodoParameter = pilDPeriodo.HasValue ?
                new ObjectParameter("pilDPeriodo", pilDPeriodo) :
                new ObjectParameter("pilDPeriodo", typeof(int));
    
            var pnTasaVehicularDebitoParameter = pnTasaVehicularDebito.HasValue ?
                new ObjectParameter("pnTasaVehicularDebito", pnTasaVehicularDebito) :
                new ObjectParameter("pnTasaVehicularDebito", typeof(decimal));
    
            var pnTasaVehicularCreditoParameter = pnTasaVehicularCredito.HasValue ?
                new ObjectParameter("pnTasaVehicularCredito", pnTasaVehicularCredito) :
                new ObjectParameter("pnTasaVehicularCredito", typeof(decimal));
    
            var pnTasaVehicularSaldoParameter = pnTasaVehicularSaldo.HasValue ?
                new ObjectParameter("pnTasaVehicularSaldo", pnTasaVehicularSaldo) :
                new ObjectParameter("pnTasaVehicularSaldo", typeof(decimal));
    
            var pnMultaVehicularDebitoParameter = pnMultaVehicularDebito.HasValue ?
                new ObjectParameter("pnMultaVehicularDebito", pnMultaVehicularDebito) :
                new ObjectParameter("pnMultaVehicularDebito", typeof(decimal));
    
            var pnMultaVehicularCreditoParameter = pnMultaVehicularCredito.HasValue ?
                new ObjectParameter("pnMultaVehicularCredito", pnMultaVehicularCredito) :
                new ObjectParameter("pnMultaVehicularCredito", typeof(decimal));
    
            var pnMultaVehicularSaldoParameter = pnMultaVehicularSaldo.HasValue ?
                new ObjectParameter("pnMultaVehicularSaldo", pnMultaVehicularSaldo) :
                new ObjectParameter("pnMultaVehicularSaldo", typeof(decimal));
    
            var pnSaldosAnterioresVehicularDebitoParameter = pnSaldosAnterioresVehicularDebito.HasValue ?
                new ObjectParameter("pnSaldosAnterioresVehicularDebito", pnSaldosAnterioresVehicularDebito) :
                new ObjectParameter("pnSaldosAnterioresVehicularDebito", typeof(decimal));
    
            var pnSaldosAnterioresVehicularCreditoParameter = pnSaldosAnterioresVehicularCredito.HasValue ?
                new ObjectParameter("pnSaldosAnterioresVehicularCredito", pnSaldosAnterioresVehicularCredito) :
                new ObjectParameter("pnSaldosAnterioresVehicularCredito", typeof(decimal));
    
            var pnSaldosAnterioresVehicularSaldoParameter = pnSaldosAnterioresVehicularSaldo.HasValue ?
                new ObjectParameter("pnSaldosAnterioresVehicularSaldo", pnSaldosAnterioresVehicularSaldo) :
                new ObjectParameter("pnSaldosAnterioresVehicularSaldo", typeof(decimal));
    
            var pnTasaMunicipalDebitoParameter = pnTasaMunicipalDebito.HasValue ?
                new ObjectParameter("pnTasaMunicipalDebito", pnTasaMunicipalDebito) :
                new ObjectParameter("pnTasaMunicipalDebito", typeof(decimal));
    
            var pnTasaMunicipalCreditoParameter = pnTasaMunicipalCredito.HasValue ?
                new ObjectParameter("pnTasaMunicipalCredito", pnTasaMunicipalCredito) :
                new ObjectParameter("pnTasaMunicipalCredito", typeof(decimal));
    
            var pnTasaMunicipalSaldoParameter = pnTasaMunicipalSaldo.HasValue ?
                new ObjectParameter("pnTasaMunicipalSaldo", pnTasaMunicipalSaldo) :
                new ObjectParameter("pnTasaMunicipalSaldo", typeof(decimal));
    
            var pnMultaMunicipalDebitoParameter = pnMultaMunicipalDebito.HasValue ?
                new ObjectParameter("pnMultaMunicipalDebito", pnMultaMunicipalDebito) :
                new ObjectParameter("pnMultaMunicipalDebito", typeof(decimal));
    
            var pnMultaMunicipalCreditoParameter = pnMultaMunicipalCredito.HasValue ?
                new ObjectParameter("pnMultaMunicipalCredito", pnMultaMunicipalCredito) :
                new ObjectParameter("pnMultaMunicipalCredito", typeof(decimal));
    
            var pnMultaMunicipalSaldoParameter = pnMultaMunicipalSaldo.HasValue ?
                new ObjectParameter("pnMultaMunicipalSaldo", pnMultaMunicipalSaldo) :
                new ObjectParameter("pnMultaMunicipalSaldo", typeof(decimal));
    
            var pnSaldosAnterioresMunicipalesDebitoParameter = pnSaldosAnterioresMunicipalesDebito.HasValue ?
                new ObjectParameter("pnSaldosAnterioresMunicipalesDebito", pnSaldosAnterioresMunicipalesDebito) :
                new ObjectParameter("pnSaldosAnterioresMunicipalesDebito", typeof(decimal));
    
            var pnSaldosAnterioresMunicipalesCreditoParameter = pnSaldosAnterioresMunicipalesCredito.HasValue ?
                new ObjectParameter("pnSaldosAnterioresMunicipalesCredito", pnSaldosAnterioresMunicipalesCredito) :
                new ObjectParameter("pnSaldosAnterioresMunicipalesCredito", typeof(decimal));
    
            var pnSaldosAnterioresMunicipalesSaldoParameter = pnSaldosAnterioresMunicipalesSaldo.HasValue ?
                new ObjectParameter("pnSaldosAnterioresMunicipalesSaldo", pnSaldosAnterioresMunicipalesSaldo) :
                new ObjectParameter("pnSaldosAnterioresMunicipalesSaldo", typeof(decimal));
    
            var pnContribucionSigloXXIDebitoParameter = pnContribucionSigloXXIDebito.HasValue ?
                new ObjectParameter("pnContribucionSigloXXIDebito", pnContribucionSigloXXIDebito) :
                new ObjectParameter("pnContribucionSigloXXIDebito", typeof(decimal));
    
            var pnContribucionSigloXXICreditoParameter = pnContribucionSigloXXICredito.HasValue ?
                new ObjectParameter("pnContribucionSigloXXICredito", pnContribucionSigloXXICredito) :
                new ObjectParameter("pnContribucionSigloXXICredito", typeof(decimal));
    
            var pnContribucionSigloXXISaldoParameter = pnContribucionSigloXXISaldo.HasValue ?
                new ObjectParameter("pnContribucionSigloXXISaldo", pnContribucionSigloXXISaldo) :
                new ObjectParameter("pnContribucionSigloXXISaldo", typeof(decimal));
    
            var pnSaldosAnterioresSigloXXIDebitoParameter = pnSaldosAnterioresSigloXXIDebito.HasValue ?
                new ObjectParameter("pnSaldosAnterioresSigloXXIDebito", pnSaldosAnterioresSigloXXIDebito) :
                new ObjectParameter("pnSaldosAnterioresSigloXXIDebito", typeof(decimal));
    
            var pnSaldosAnterioresSiglosXXICreditoParameter = pnSaldosAnterioresSiglosXXICredito.HasValue ?
                new ObjectParameter("pnSaldosAnterioresSiglosXXICredito", pnSaldosAnterioresSiglosXXICredito) :
                new ObjectParameter("pnSaldosAnterioresSiglosXXICredito", typeof(decimal));
    
            var pnSaldosAnterioresSiglosXXISaldoParameter = pnSaldosAnterioresSiglosXXISaldo.HasValue ?
                new ObjectParameter("pnSaldosAnterioresSiglosXXISaldo", pnSaldosAnterioresSiglosXXISaldo) :
                new ObjectParameter("pnSaldosAnterioresSiglosXXISaldo", typeof(decimal));
    
            var pnValorPlacaDebitoParameter = pnValorPlacaDebito.HasValue ?
                new ObjectParameter("pnValorPlacaDebito", pnValorPlacaDebito) :
                new ObjectParameter("pnValorPlacaDebito", typeof(decimal));
    
            var pnValorPlacaCreditoParameter = pnValorPlacaCredito.HasValue ?
                new ObjectParameter("pnValorPlacaCredito", pnValorPlacaCredito) :
                new ObjectParameter("pnValorPlacaCredito", typeof(decimal));
    
            var pnValorPlacaSaldoParameter = pnValorPlacaSaldo.HasValue ?
                new ObjectParameter("pnValorPlacaSaldo", pnValorPlacaSaldo) :
                new ObjectParameter("pnValorPlacaSaldo", typeof(decimal));
    
            var pilDTotalMatriculaParameter = pilDTotalMatricula.HasValue ?
                new ObjectParameter("pilDTotalMatricula", pilDTotalMatricula) :
                new ObjectParameter("pilDTotalMatricula", typeof(decimal));
    
            var piCambiodePropietarioCantidadParameter = piCambiodePropietarioCantidad.HasValue ?
                new ObjectParameter("piCambiodePropietarioCantidad", piCambiodePropietarioCantidad) :
                new ObjectParameter("piCambiodePropietarioCantidad", typeof(int));
    
            var pnCambiodePropietarioMontoParameter = pnCambiodePropietarioMonto.HasValue ?
                new ObjectParameter("pnCambiodePropietarioMonto", pnCambiodePropietarioMonto) :
                new ObjectParameter("pnCambiodePropietarioMonto", typeof(decimal));
    
            var piCambioPlacaCantidadParameter = piCambioPlacaCantidad.HasValue ?
                new ObjectParameter("piCambioPlacaCantidad", piCambioPlacaCantidad) :
                new ObjectParameter("piCambioPlacaCantidad", typeof(int));
    
            var pnCambioPlacaMontoParameter = pnCambioPlacaMonto.HasValue ?
                new ObjectParameter("pnCambioPlacaMonto", pnCambioPlacaMonto) :
                new ObjectParameter("pnCambioPlacaMonto", typeof(decimal));
    
            var piTotalCantidadParameter = piTotalCantidad.HasValue ?
                new ObjectParameter("piTotalCantidad", piTotalCantidad) :
                new ObjectParameter("piTotalCantidad", typeof(int));
    
            var pnTotalMontoParameter = pnTotalMonto.HasValue ?
                new ObjectParameter("pnTotalMonto", pnTotalMonto) :
                new ObjectParameter("pnTotalMonto", typeof(decimal));
    
            var pnTotalaPagarParameter = pnTotalaPagar.HasValue ?
                new ObjectParameter("pnTotalaPagar", pnTotalaPagar) :
                new ObjectParameter("pnTotalaPagar", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_IncertarConsultaPlacaIP", pcPlacaParameter, pcMarcaParameter, pcColorParameter, pilDPeriodoParameter, pnTasaVehicularDebitoParameter, pnTasaVehicularCreditoParameter, pnTasaVehicularSaldoParameter, pnMultaVehicularDebitoParameter, pnMultaVehicularCreditoParameter, pnMultaVehicularSaldoParameter, pnSaldosAnterioresVehicularDebitoParameter, pnSaldosAnterioresVehicularCreditoParameter, pnSaldosAnterioresVehicularSaldoParameter, pnTasaMunicipalDebitoParameter, pnTasaMunicipalCreditoParameter, pnTasaMunicipalSaldoParameter, pnMultaMunicipalDebitoParameter, pnMultaMunicipalCreditoParameter, pnMultaMunicipalSaldoParameter, pnSaldosAnterioresMunicipalesDebitoParameter, pnSaldosAnterioresMunicipalesCreditoParameter, pnSaldosAnterioresMunicipalesSaldoParameter, pnContribucionSigloXXIDebitoParameter, pnContribucionSigloXXICreditoParameter, pnContribucionSigloXXISaldoParameter, pnSaldosAnterioresSigloXXIDebitoParameter, pnSaldosAnterioresSiglosXXICreditoParameter, pnSaldosAnterioresSiglosXXISaldoParameter, pnValorPlacaDebitoParameter, pnValorPlacaCreditoParameter, pnValorPlacaSaldoParameter, pilDTotalMatriculaParameter, piCambiodePropietarioCantidadParameter, pnCambiodePropietarioMontoParameter, piCambioPlacaCantidadParameter, pnCambioPlacaMontoParameter, piTotalCantidadParameter, pnTotalMontoParameter, pnTotalaPagarParameter);
        }
    
        public virtual ObjectResult<string> sp_Manuales_Documentos_Guardar(Nullable<int> piIDSolicitudManual, Nullable<int> piIDUsuarioCreador, Nullable<int> piNumeroPagina, string pcTipoArchivo, string pcNombreArchivo, string pcRutaArchivo, string pcURL, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSolicitudManualParameter = piIDSolicitudManual.HasValue ?
                new ObjectParameter("piIDSolicitudManual", piIDSolicitudManual) :
                new ObjectParameter("piIDSolicitudManual", typeof(int));
    
            var piIDUsuarioCreadorParameter = piIDUsuarioCreador.HasValue ?
                new ObjectParameter("piIDUsuarioCreador", piIDUsuarioCreador) :
                new ObjectParameter("piIDUsuarioCreador", typeof(int));
    
            var piNumeroPaginaParameter = piNumeroPagina.HasValue ?
                new ObjectParameter("piNumeroPagina", piNumeroPagina) :
                new ObjectParameter("piNumeroPagina", typeof(int));
    
            var pcTipoArchivoParameter = pcTipoArchivo != null ?
                new ObjectParameter("pcTipoArchivo", pcTipoArchivo) :
                new ObjectParameter("pcTipoArchivo", typeof(string));
    
            var pcNombreArchivoParameter = pcNombreArchivo != null ?
                new ObjectParameter("pcNombreArchivo", pcNombreArchivo) :
                new ObjectParameter("pcNombreArchivo", typeof(string));
    
            var pcRutaArchivoParameter = pcRutaArchivo != null ?
                new ObjectParameter("pcRutaArchivo", pcRutaArchivo) :
                new ObjectParameter("pcRutaArchivo", typeof(string));
    
            var pcURLParameter = pcURL != null ?
                new ObjectParameter("pcURL", pcURL) :
                new ObjectParameter("pcURL", typeof(string));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Manuales_Documentos_Guardar", piIDSolicitudManualParameter, piIDUsuarioCreadorParameter, piNumeroPaginaParameter, pcTipoArchivoParameter, pcNombreArchivoParameter, pcRutaArchivoParameter, pcURLParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_Manuales_Paginas_ObtenerPorIdManual_Result> sp_Manuales_Paginas_ObtenerPorIdManual(Nullable<int> piIDManual, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDManualParameter = piIDManual.HasValue ?
                new ObjectParameter("piIDManual", piIDManual) :
                new ObjectParameter("piIDManual", typeof(int));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Manuales_Paginas_ObtenerPorIdManual_Result>("sp_Manuales_Paginas_ObtenerPorIdManual", piIDManualParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_MostrarInfo_PlacaIP_Result> sp_MostrarInfo_PlacaIP(string pcPlaca)
        {
            var pcPlacaParameter = pcPlaca != null ?
                new ObjectParameter("pcPlaca", pcPlaca) :
                new ObjectParameter("pcPlaca", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_MostrarInfo_PlacaIP_Result>("sp_MostrarInfo_PlacaIP", pcPlacaParameter);
        }
    
        public virtual int sp_NumeroConsecutivo(Nullable<int> piIDContador, ObjectParameter poiSiguienteNumero)
        {
            var piIDContadorParameter = piIDContador.HasValue ?
                new ObjectParameter("piIDContador", piIDContador) :
                new ObjectParameter("piIDContador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NumeroConsecutivo", piIDContadorParameter, poiSiguienteNumero);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Requerimiento_Agregar(Nullable<int> piIDUsuario, string pcIP, string pcTituloRequerimiento, string pcDescripcionRequerimiento, Nullable<byte> piTipoRequerimiento, Nullable<int> piIDAreaSolicitante)
        {
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var pcIPParameter = pcIP != null ?
                new ObjectParameter("pcIP", pcIP) :
                new ObjectParameter("pcIP", typeof(string));
    
            var pcTituloRequerimientoParameter = pcTituloRequerimiento != null ?
                new ObjectParameter("pcTituloRequerimiento", pcTituloRequerimiento) :
                new ObjectParameter("pcTituloRequerimiento", typeof(string));
    
            var pcDescripcionRequerimientoParameter = pcDescripcionRequerimiento != null ?
                new ObjectParameter("pcDescripcionRequerimiento", pcDescripcionRequerimiento) :
                new ObjectParameter("pcDescripcionRequerimiento", typeof(string));
    
            var piTipoRequerimientoParameter = piTipoRequerimiento.HasValue ?
                new ObjectParameter("piTipoRequerimiento", piTipoRequerimiento) :
                new ObjectParameter("piTipoRequerimiento", typeof(byte));
    
            var piIDAreaSolicitanteParameter = piIDAreaSolicitante.HasValue ?
                new ObjectParameter("piIDAreaSolicitante", piIDAreaSolicitante) :
                new ObjectParameter("piIDAreaSolicitante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Requerimiento_Agregar", piIDUsuarioParameter, pcIPParameter, pcTituloRequerimientoParameter, pcDescripcionRequerimientoParameter, piTipoRequerimientoParameter, piIDAreaSolicitanteParameter);
        }
    
        public virtual ObjectResult<string> sp_Requerimiento_Alta(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario, string pcDescripcion, string pcTituloRequerimiento, string pcDetalleRequerimiento, Nullable<byte> piEstadoRequerimiento)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var pcDescripcionParameter = pcDescripcion != null ?
                new ObjectParameter("pcDescripcion", pcDescripcion) :
                new ObjectParameter("pcDescripcion", typeof(string));
    
            var pcTituloRequerimientoParameter = pcTituloRequerimiento != null ?
                new ObjectParameter("pcTituloRequerimiento", pcTituloRequerimiento) :
                new ObjectParameter("pcTituloRequerimiento", typeof(string));
    
            var pcDetalleRequerimientoParameter = pcDetalleRequerimiento != null ?
                new ObjectParameter("pcDetalleRequerimiento", pcDetalleRequerimiento) :
                new ObjectParameter("pcDetalleRequerimiento", typeof(string));
    
            var piEstadoRequerimientoParameter = piEstadoRequerimiento.HasValue ?
                new ObjectParameter("piEstadoRequerimiento", piEstadoRequerimiento) :
                new ObjectParameter("piEstadoRequerimiento", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Requerimiento_Alta", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter, pcDescripcionParameter, pcTituloRequerimientoParameter, pcDetalleRequerimientoParameter, piEstadoRequerimientoParameter);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Areas_Result> sp_Requerimiento_Areas(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Areas_Result>("sp_Requerimiento_Areas", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Documentos_ObtenerPorIdRequerimiento_Result> sp_Requerimiento_Documentos_ObtenerPorIdRequerimiento(Nullable<int> piIDRequerimiento, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Documentos_ObtenerPorIdRequerimiento_Result>("sp_Requerimiento_Documentos_ObtenerPorIdRequerimiento", piIDRequerimientoParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual int sp_Requerimiento_Indicadores(Nullable<System.DateTime> pdFechaOperativa)
        {
            var pdFechaOperativaParameter = pdFechaOperativa.HasValue ?
                new ObjectParameter("pdFechaOperativa", pdFechaOperativa) :
                new ObjectParameter("pdFechaOperativa", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Requerimiento_Indicadores", pdFechaOperativaParameter);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Lista_Result> sp_Requerimiento_Lista(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Lista_Result>("sp_Requerimiento_Lista", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<string> sp_Requerimiento_Maestro_Actualizar(Nullable<int> piIDUsuario, Nullable<int> piIDRequerimiento, string pcTituloRequerimiento, string pcDescripcionRequerimiento, Nullable<byte> piIDEstadoRequerimiento, Nullable<System.DateTime> fdFechaAsignacion, Nullable<int> pifiIDUsuarioAsignado, Nullable<int> piTiempodeDesarrollo, Nullable<byte> pifiTipoRequerimiento, Nullable<int> piIDApp)
        {
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            var pcTituloRequerimientoParameter = pcTituloRequerimiento != null ?
                new ObjectParameter("pcTituloRequerimiento", pcTituloRequerimiento) :
                new ObjectParameter("pcTituloRequerimiento", typeof(string));
    
            var pcDescripcionRequerimientoParameter = pcDescripcionRequerimiento != null ?
                new ObjectParameter("pcDescripcionRequerimiento", pcDescripcionRequerimiento) :
                new ObjectParameter("pcDescripcionRequerimiento", typeof(string));
    
            var piIDEstadoRequerimientoParameter = piIDEstadoRequerimiento.HasValue ?
                new ObjectParameter("piIDEstadoRequerimiento", piIDEstadoRequerimiento) :
                new ObjectParameter("piIDEstadoRequerimiento", typeof(byte));
    
            var fdFechaAsignacionParameter = fdFechaAsignacion.HasValue ?
                new ObjectParameter("fdFechaAsignacion", fdFechaAsignacion) :
                new ObjectParameter("fdFechaAsignacion", typeof(System.DateTime));
    
            var pifiIDUsuarioAsignadoParameter = pifiIDUsuarioAsignado.HasValue ?
                new ObjectParameter("pifiIDUsuarioAsignado", pifiIDUsuarioAsignado) :
                new ObjectParameter("pifiIDUsuarioAsignado", typeof(int));
    
            var piTiempodeDesarrolloParameter = piTiempodeDesarrollo.HasValue ?
                new ObjectParameter("piTiempodeDesarrollo", piTiempodeDesarrollo) :
                new ObjectParameter("piTiempodeDesarrollo", typeof(int));
    
            var pifiTipoRequerimientoParameter = pifiTipoRequerimiento.HasValue ?
                new ObjectParameter("pifiTipoRequerimiento", pifiTipoRequerimiento) :
                new ObjectParameter("pifiTipoRequerimiento", typeof(byte));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Requerimiento_Maestro_Actualizar", piIDUsuarioParameter, piIDRequerimientoParameter, pcTituloRequerimientoParameter, pcDescripcionRequerimientoParameter, piIDEstadoRequerimientoParameter, fdFechaAsignacionParameter, pifiIDUsuarioAsignadoParameter, piTiempodeDesarrolloParameter, pifiTipoRequerimientoParameter, piIDAppParameter);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Maestro_Detalle_Result> sp_Requerimiento_Maestro_Detalle(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario, Nullable<int> piIDRequerimiento)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Maestro_Detalle_Result>("sp_Requerimiento_Maestro_Detalle", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter, piIDRequerimientoParameter);
        }
    
        public virtual int sp_Requerimiento_NumeroConsecutivo(Nullable<int> piIDContador, ObjectParameter poiSiguienteNumero)
        {
            var piIDContadorParameter = piIDContador.HasValue ?
                new ObjectParameter("piIDContador", piIDContador) :
                new ObjectParameter("piIDContador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Requerimiento_NumeroConsecutivo", piIDContadorParameter, poiSiguienteNumero);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Tipo_Adjuntos_Result> sp_Requerimiento_Tipo_Adjuntos(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Tipo_Adjuntos_Result>("sp_Requerimiento_Tipo_Adjuntos", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<string> sp_RequerimientoBitacoras_Agregar(Nullable<int> piIDUsuario, Nullable<int> piIDRequerimiento, Nullable<int> piIDUsuarioSolicitante, string fcComentario, Nullable<int> piIDApp, Nullable<int> piIDEstado)
        {
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            var piIDUsuarioSolicitanteParameter = piIDUsuarioSolicitante.HasValue ?
                new ObjectParameter("piIDUsuarioSolicitante", piIDUsuarioSolicitante) :
                new ObjectParameter("piIDUsuarioSolicitante", typeof(int));
    
            var fcComentarioParameter = fcComentario != null ?
                new ObjectParameter("fcComentario", fcComentario) :
                new ObjectParameter("fcComentario", typeof(string));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDEstadoParameter = piIDEstado.HasValue ?
                new ObjectParameter("piIDEstado", piIDEstado) :
                new ObjectParameter("piIDEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_RequerimientoBitacoras_Agregar", piIDUsuarioParameter, piIDRequerimientoParameter, piIDUsuarioSolicitanteParameter, fcComentarioParameter, piIDAppParameter, piIDEstadoParameter);
        }
    
        public virtual ObjectResult<sp_RequerimientoBitacoras_Detalle_Result> sp_RequerimientoBitacoras_Detalle(Nullable<int> piIDUsuario, Nullable<int> piIDRequerimiento, Nullable<int> piIDApp)
        {
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_RequerimientoBitacoras_Detalle_Result>("sp_RequerimientoBitacoras_Detalle", piIDUsuarioParameter, piIDRequerimientoParameter, piIDAppParameter);
        }
    
        public virtual ObjectResult<string> sp_Requerimientos_Adjuntos_Guardar(Nullable<int> piIDRequerimiento, string pcNombreArchivo, string pcTipoArchivo, string pcRutaArchivo, string pcURL, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            var pcNombreArchivoParameter = pcNombreArchivo != null ?
                new ObjectParameter("pcNombreArchivo", pcNombreArchivo) :
                new ObjectParameter("pcNombreArchivo", typeof(string));
    
            var pcTipoArchivoParameter = pcTipoArchivo != null ?
                new ObjectParameter("pcTipoArchivo", pcTipoArchivo) :
                new ObjectParameter("pcTipoArchivo", typeof(string));
    
            var pcRutaArchivoParameter = pcRutaArchivo != null ?
                new ObjectParameter("pcRutaArchivo", pcRutaArchivo) :
                new ObjectParameter("pcRutaArchivo", typeof(string));
    
            var pcURLParameter = pcURL != null ?
                new ObjectParameter("pcURL", pcURL) :
                new ObjectParameter("pcURL", typeof(string));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Requerimientos_Adjuntos_Guardar", piIDRequerimientoParameter, pcNombreArchivoParameter, pcTipoArchivoParameter, pcRutaArchivoParameter, pcURLParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual int sp_Requerimientos_Bitacoras_Estados(Nullable<int> piIDRequerimiento)
        {
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Requerimientos_Bitacoras_Estados", piIDRequerimientoParameter);
        }
    
        public virtual int sp_Tutoriales_AccesosAreas_Actualizar(Nullable<int> fiIDEmpleado, Nullable<int> fiIDArea, Nullable<int> fiIDAcceso)
        {
            var fiIDEmpleadoParameter = fiIDEmpleado.HasValue ?
                new ObjectParameter("fiIDEmpleado", fiIDEmpleado) :
                new ObjectParameter("fiIDEmpleado", typeof(int));
    
            var fiIDAreaParameter = fiIDArea.HasValue ?
                new ObjectParameter("fiIDArea", fiIDArea) :
                new ObjectParameter("fiIDArea", typeof(int));
    
            var fiIDAccesoParameter = fiIDAcceso.HasValue ?
                new ObjectParameter("fiIDAcceso", fiIDAcceso) :
                new ObjectParameter("fiIDAcceso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Tutoriales_AccesosAreas_Actualizar", fiIDEmpleadoParameter, fiIDAreaParameter, fiIDAccesoParameter);
        }
    
        public virtual int sp_Tutoriales_AccesosAreas_Insert(Nullable<int> fiIDEmpleado, Nullable<int> fiIDArea)
        {
            var fiIDEmpleadoParameter = fiIDEmpleado.HasValue ?
                new ObjectParameter("fiIDEmpleado", fiIDEmpleado) :
                new ObjectParameter("fiIDEmpleado", typeof(int));
    
            var fiIDAreaParameter = fiIDArea.HasValue ?
                new ObjectParameter("fiIDArea", fiIDArea) :
                new ObjectParameter("fiIDArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Tutoriales_AccesosAreas_Insert", fiIDEmpleadoParameter, fiIDAreaParameter);
        }
    
        public virtual int sp_Tutoriales_Videos_Insert(string fcDescripcionVideo, Nullable<int> fiIDArea, string fcUrl, string fcNombreArchivo)
        {
            var fcDescripcionVideoParameter = fcDescripcionVideo != null ?
                new ObjectParameter("fcDescripcionVideo", fcDescripcionVideo) :
                new ObjectParameter("fcDescripcionVideo", typeof(string));
    
            var fiIDAreaParameter = fiIDArea.HasValue ?
                new ObjectParameter("fiIDArea", fiIDArea) :
                new ObjectParameter("fiIDArea", typeof(int));
    
            var fcUrlParameter = fcUrl != null ?
                new ObjectParameter("fcUrl", fcUrl) :
                new ObjectParameter("fcUrl", typeof(string));
    
            var fcNombreArchivoParameter = fcNombreArchivo != null ?
                new ObjectParameter("fcNombreArchivo", fcNombreArchivo) :
                new ObjectParameter("fcNombreArchivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Tutoriales_Videos_Insert", fcDescripcionVideoParameter, fiIDAreaParameter, fcUrlParameter, fcNombreArchivoParameter);
        }
    
        public virtual ObjectResult<sp_tutorialesList_byIdArea_Result> sp_tutorialesList_byIdArea(Nullable<int> fiIdArea)
        {
            var fiIdAreaParameter = fiIdArea.HasValue ?
                new ObjectParameter("fiIdArea", fiIdArea) :
                new ObjectParameter("fiIdArea", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_tutorialesList_byIdArea_Result>("sp_tutorialesList_byIdArea", fiIdAreaParameter);
        }
    }
}
