//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OrionCoreCableColor.DbConnection
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using System.Data.SqlClient;

    public partial class SARISEntities1 : DbContext
    {
        public SARISEntities1()
            : base("name=SARISEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {

            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<Nullable<int>> Multiplicacion(Nullable<int> numero1, Nullable<int> numero2)
        {
            var numero1Parameter = numero1.HasValue ?
                new ObjectParameter("numero1", numero1) :
                new ObjectParameter("numero1", typeof(int));
    
            var numero2Parameter = numero2.HasValue ?
                new ObjectParameter("numero2", numero2) :
                new ObjectParameter("numero2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Multiplicacion", numero1Parameter, numero2Parameter);
        }
    
        public virtual int sp_NumeroConsecutivo(Nullable<int> piIDContador, ObjectParameter poiSiguienteNumero)
        {
            var piIDContadorParameter = piIDContador.HasValue ?
                new ObjectParameter("piIDContador", piIDContador) :
                new ObjectParameter("piIDContador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_NumeroConsecutivo", piIDContadorParameter, poiSiguienteNumero);
        }
    
        public virtual ObjectResult<Nullable<int>> sp_Requerimiento_Agregar(Nullable<int> piIDUsuario, string pcIP, string pcTituloRequerimiento, string pcDescripcionRequerimiento, Nullable<byte> piTipoRequerimiento, Nullable<int> piIDAreaSolicitante)
        {
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var pcIPParameter = pcIP != null ?
                new ObjectParameter("pcIP", pcIP) :
                new ObjectParameter("pcIP", typeof(string));
    
            var pcTituloRequerimientoParameter = pcTituloRequerimiento != null ?
                new ObjectParameter("pcTituloRequerimiento", pcTituloRequerimiento) :
                new ObjectParameter("pcTituloRequerimiento", typeof(string));
    
            var pcDescripcionRequerimientoParameter = pcDescripcionRequerimiento != null ?
                new ObjectParameter("pcDescripcionRequerimiento", pcDescripcionRequerimiento) :
                new ObjectParameter("pcDescripcionRequerimiento", typeof(string));
    
            var piTipoRequerimientoParameter = piTipoRequerimiento.HasValue ?
                new ObjectParameter("piTipoRequerimiento", piTipoRequerimiento) :
                new ObjectParameter("piTipoRequerimiento", typeof(byte));
    
            var piIDAreaSolicitanteParameter = piIDAreaSolicitante.HasValue ?
                new ObjectParameter("piIDAreaSolicitante", piIDAreaSolicitante) :
                new ObjectParameter("piIDAreaSolicitante", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("sp_Requerimiento_Agregar", piIDUsuarioParameter, pcIPParameter, pcTituloRequerimientoParameter, pcDescripcionRequerimientoParameter, piTipoRequerimientoParameter, piIDAreaSolicitanteParameter);
        }
    
        public virtual ObjectResult<string> sp_Requerimiento_Alta(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario, string pcDescripcion, string pcTituloRequerimiento, string pcDetalleRequerimiento, Nullable<byte> piEstadoRequerimiento)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var pcDescripcionParameter = pcDescripcion != null ?
                new ObjectParameter("pcDescripcion", pcDescripcion) :
                new ObjectParameter("pcDescripcion", typeof(string));
    
            var pcTituloRequerimientoParameter = pcTituloRequerimiento != null ?
                new ObjectParameter("pcTituloRequerimiento", pcTituloRequerimiento) :
                new ObjectParameter("pcTituloRequerimiento", typeof(string));
    
            var pcDetalleRequerimientoParameter = pcDetalleRequerimiento != null ?
                new ObjectParameter("pcDetalleRequerimiento", pcDetalleRequerimiento) :
                new ObjectParameter("pcDetalleRequerimiento", typeof(string));
    
            var piEstadoRequerimientoParameter = piEstadoRequerimiento.HasValue ?
                new ObjectParameter("piEstadoRequerimiento", piEstadoRequerimiento) :
                new ObjectParameter("piEstadoRequerimiento", typeof(byte));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Requerimiento_Alta", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter, pcDescripcionParameter, pcTituloRequerimientoParameter, pcDetalleRequerimientoParameter, piEstadoRequerimientoParameter);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Areas_Result> sp_Requerimiento_Areas(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Areas_Result>("sp_Requerimiento_Areas", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<string> sp_Requerimiento_Bitacoras_Agregar(Nullable<int> piIDUsuario, Nullable<int> piIDRequerimiento, Nullable<int> piIDUsuarioSolicitante, string fcComentario, Nullable<int> piIDApp, Nullable<int> piIDEstado)
        {
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            var piIDUsuarioSolicitanteParameter = piIDUsuarioSolicitante.HasValue ?
                new ObjectParameter("piIDUsuarioSolicitante", piIDUsuarioSolicitante) :
                new ObjectParameter("piIDUsuarioSolicitante", typeof(int));
    
            var fcComentarioParameter = fcComentario != null ?
                new ObjectParameter("fcComentario", fcComentario) :
                new ObjectParameter("fcComentario", typeof(string));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDEstadoParameter = piIDEstado.HasValue ?
                new ObjectParameter("piIDEstado", piIDEstado) :
                new ObjectParameter("piIDEstado", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Requerimiento_Bitacoras_Agregar", piIDUsuarioParameter, piIDRequerimientoParameter, piIDUsuarioSolicitanteParameter, fcComentarioParameter, piIDAppParameter, piIDEstadoParameter);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Bitacoras_Detalle_Result> sp_Requerimiento_Bitacoras_Detalle(Nullable<int> piIDUsuario, Nullable<int> piIDRequerimiento, Nullable<int> piIDApp)
        {
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Bitacoras_Detalle_Result>("sp_Requerimiento_Bitacoras_Detalle", piIDUsuarioParameter, piIDRequerimientoParameter, piIDAppParameter);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Documentos_ObtenerPorIdRequerimiento_Result> sp_Requerimiento_Documentos_ObtenerPorIdRequerimiento(Nullable<int> piIDRequerimiento, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Documentos_ObtenerPorIdRequerimiento_Result>("sp_Requerimiento_Documentos_ObtenerPorIdRequerimiento", piIDRequerimientoParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Estados_Result> sp_Requerimiento_Estados(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Estados_Result>("sp_Requerimiento_Estados", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual int sp_Requerimiento_Indicadores(Nullable<System.DateTime> pdFechaOperativa)
        {
            var pdFechaOperativaParameter = pdFechaOperativa.HasValue ?
                new ObjectParameter("pdFechaOperativa", pdFechaOperativa) :
                new ObjectParameter("pdFechaOperativa", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Requerimiento_Indicadores", pdFechaOperativaParameter);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Lista_Result> sp_Requerimiento_Lista(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Lista_Result>("sp_Requerimiento_Lista", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<string> sp_Requerimiento_Maestro_Actualizar(Nullable<int> piIDUsuario, Nullable<int> piIDRequerimiento, string pcTituloRequerimiento, string pcDescripcionRequerimiento, Nullable<byte> piIDEstadoRequerimiento, Nullable<System.DateTime> fdFechaAsignacion, Nullable<int> pifiIDUsuarioAsignado, Nullable<int> piTiempodeDesarrollo, Nullable<byte> pifiTipoRequerimiento, Nullable<int> piIDApp)
        {
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            var pcTituloRequerimientoParameter = pcTituloRequerimiento != null ?
                new ObjectParameter("pcTituloRequerimiento", pcTituloRequerimiento) :
                new ObjectParameter("pcTituloRequerimiento", typeof(string));
    
            var pcDescripcionRequerimientoParameter = pcDescripcionRequerimiento != null ?
                new ObjectParameter("pcDescripcionRequerimiento", pcDescripcionRequerimiento) :
                new ObjectParameter("pcDescripcionRequerimiento", typeof(string));
    
            var piIDEstadoRequerimientoParameter = piIDEstadoRequerimiento.HasValue ?
                new ObjectParameter("piIDEstadoRequerimiento", piIDEstadoRequerimiento) :
                new ObjectParameter("piIDEstadoRequerimiento", typeof(byte));
    
            var fdFechaAsignacionParameter = fdFechaAsignacion.HasValue ?
                new ObjectParameter("fdFechaAsignacion", fdFechaAsignacion) :
                new ObjectParameter("fdFechaAsignacion", typeof(System.DateTime));
    
            var pifiIDUsuarioAsignadoParameter = pifiIDUsuarioAsignado.HasValue ?
                new ObjectParameter("pifiIDUsuarioAsignado", pifiIDUsuarioAsignado) :
                new ObjectParameter("pifiIDUsuarioAsignado", typeof(int));
    
            var piTiempodeDesarrolloParameter = piTiempodeDesarrollo.HasValue ?
                new ObjectParameter("piTiempodeDesarrollo", piTiempodeDesarrollo) :
                new ObjectParameter("piTiempodeDesarrollo", typeof(int));
    
            var pifiTipoRequerimientoParameter = pifiTipoRequerimiento.HasValue ?
                new ObjectParameter("pifiTipoRequerimiento", pifiTipoRequerimiento) :
                new ObjectParameter("pifiTipoRequerimiento", typeof(byte));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Requerimiento_Maestro_Actualizar", piIDUsuarioParameter, piIDRequerimientoParameter, pcTituloRequerimientoParameter, pcDescripcionRequerimientoParameter, piIDEstadoRequerimientoParameter, fdFechaAsignacionParameter, pifiIDUsuarioAsignadoParameter, piTiempodeDesarrolloParameter, pifiTipoRequerimientoParameter, piIDAppParameter);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Maestro_Detalle_Result> sp_Requerimiento_Maestro_Detalle(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario, Nullable<int> piIDRequerimiento)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Maestro_Detalle_Result>("sp_Requerimiento_Maestro_Detalle", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter, piIDRequerimientoParameter);
        }
    
        public virtual int sp_Requerimiento_NumeroConsecutivo(Nullable<int> piIDContador, ObjectParameter poiSiguienteNumero)
        {
            var piIDContadorParameter = piIDContador.HasValue ?
                new ObjectParameter("piIDContador", piIDContador) :
                new ObjectParameter("piIDContador", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Requerimiento_NumeroConsecutivo", piIDContadorParameter, poiSiguienteNumero);
        }
    
        public virtual ObjectResult<sp_Requerimiento_Tipo_Adjuntos_Result> sp_Requerimiento_Tipo_Adjuntos(Nullable<int> piIDSesion, Nullable<short> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(short));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Requerimiento_Tipo_Adjuntos_Result>("sp_Requerimiento_Tipo_Adjuntos", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual ObjectResult<string> sp_Requerimientos_Adjuntos_Guardar(Nullable<int> piIDRequerimiento, string pcNombreArchivo, string pcTipoArchivo, string pcRutaArchivo, string pcURL, Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            var pcNombreArchivoParameter = pcNombreArchivo != null ?
                new ObjectParameter("pcNombreArchivo", pcNombreArchivo) :
                new ObjectParameter("pcNombreArchivo", typeof(string));
    
            var pcTipoArchivoParameter = pcTipoArchivo != null ?
                new ObjectParameter("pcTipoArchivo", pcTipoArchivo) :
                new ObjectParameter("pcTipoArchivo", typeof(string));
    
            var pcRutaArchivoParameter = pcRutaArchivo != null ?
                new ObjectParameter("pcRutaArchivo", pcRutaArchivo) :
                new ObjectParameter("pcRutaArchivo", typeof(string));
    
            var pcURLParameter = pcURL != null ?
                new ObjectParameter("pcURL", pcURL) :
                new ObjectParameter("pcURL", typeof(string));
    
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("sp_Requerimientos_Adjuntos_Guardar", piIDRequerimientoParameter, pcNombreArchivoParameter, pcTipoArchivoParameter, pcRutaArchivoParameter, pcURLParameter, piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual int sp_Requerimientos_Bandeja(Nullable<int> piIDSesion, Nullable<int> piIDApp, Nullable<int> piIDUsuario)
        {
            var piIDSesionParameter = piIDSesion.HasValue ?
                new ObjectParameter("piIDSesion", piIDSesion) :
                new ObjectParameter("piIDSesion", typeof(int));
    
            var piIDAppParameter = piIDApp.HasValue ?
                new ObjectParameter("piIDApp", piIDApp) :
                new ObjectParameter("piIDApp", typeof(int));
    
            var piIDUsuarioParameter = piIDUsuario.HasValue ?
                new ObjectParameter("piIDUsuario", piIDUsuario) :
                new ObjectParameter("piIDUsuario", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Requerimientos_Bandeja", piIDSesionParameter, piIDAppParameter, piIDUsuarioParameter);
        }
    
        public virtual int sp_Requerimientos_Bitacoras_Estados(Nullable<int> piIDRequerimiento)
        {
            var piIDRequerimientoParameter = piIDRequerimiento.HasValue ?
                new ObjectParameter("piIDRequerimiento", piIDRequerimiento) :
                new ObjectParameter("piIDRequerimiento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Requerimientos_Bitacoras_Estados", piIDRequerimientoParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> Suma(Nullable<int> numero1, Nullable<int> numero2)
        {
            var numero1Parameter = numero1.HasValue ?
                new ObjectParameter("numero1", numero1) :
                new ObjectParameter("numero1", typeof(int));
    
            var numero2Parameter = numero2.HasValue ?
                new ObjectParameter("numero2", numero2) :
                new ObjectParameter("numero2", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("Suma", numero1Parameter, numero2Parameter);
        }
    }
}
